# Generated by Django 6.0 on 2025-12-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_bookanimal_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookanimal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hayvon', 'verbose_name_plural': 'Hayvonlar'},
        ),
        migrations.AddField(
            model_name='bookanimal',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookanimal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Kuchuk'), ('cat', 'Mushuk'), ('other', 'Boshqa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', "Urg'ochi"), ('unknown', "Noma'lum")], max_length=10, null=True),
        ),
    ]
