# Generated by Django 6.0 on 2025-12-07 06:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_bookanimal_options_bookanimal_breed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Boshpana nomi')),
                ('shelter_type', models.CharField(choices=[('state', 'Davlat'), ('private', 'Xususiy'), ('volunteer', "Ko'ngilli"), ('international', 'Xalqaro')], max_length=50, verbose_name='Boshpana turi')),
                ('description', models.TextField(verbose_name='Tarif')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('capacity', models.IntegerField(verbose_name="Sig'imi")),
                ('current_animals', models.IntegerField(default=0, verbose_name='Joriy hayvonlar soni')),
                ('director', models.CharField(max_length=100, verbose_name='Rahbar')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Tashkil etilgan sana')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shelter_images/', verbose_name='Rasm')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Boshpana',
                'verbose_name_plural': 'Boshpanalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('clinic_type', models.CharField(choices=[('clinic', 'Klinika'), ('hospital', 'Shifoxona'), ('mobile', 'Mobil xizmat'), ('specialized', 'Mutaxassislik klinikasi')], max_length=50, verbose_name='Klinika turi')),
                ('description', models.TextField(verbose_name='Tarif')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('services', models.CharField(max_length=200, verbose_name='Xizmatlar')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Ish soatlari')),
                ('director', models.CharField(max_length=100, verbose_name='Rahbar')),
                ('doctors_count', models.IntegerField(default=1, verbose_name='Shifokorlar soni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veterinarian_images/', verbose_name='Rasm')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Shoshilinch xizmat')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Veterinariya',
                'verbose_name_plural': 'Veterinariyalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bookanimal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AddField(
            model_name='bookanimal',
            name='status',
            field=models.CharField(choices=[('available', 'Mavjud'), ('pending', "Ko'rib chiqilmoqda"), ('adopted', 'Asrab olingan'), ('sold', 'Sotilgan'), ('reserved', 'Band qilingan')], default='available', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='bookanimal',
            name='sterilized',
            field=models.BooleanField(default=False, verbose_name='Sterilizatsiya qilingan'),
        ),
        migrations.AddField(
            model_name='bookanimal',
            name='vaccinated',
            field=models.BooleanField(default=False, verbose_name='Emlangan'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yoshi'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Kuchuk'), ('cat', 'Mushuk'), ('bird', 'Qush'), ('rabbit', 'Quyon'), ('fish', 'Baliq'), ('rodent', 'Kemiruvchi'), ('reptile', 'Sudraluvchi'), ('other', 'Boshqa')], max_length=50, verbose_name='Hayvon turi'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoti'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', "Urg'ochi"), ('unknown', "Noma'lum")], max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='Sotiladi'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='bookanimal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Tajriba')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin izohlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='animals.bookanimal', verbose_name='Hayvon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Asrab olish so'rovi",
                'verbose_name_plural': "Asrab olish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_gallery/', verbose_name='Rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.bookanimal', verbose_name='Hayvon')),
            ],
            options={
                'verbose_name': 'Hayvon rasmi',
                'verbose_name_plural': 'Hayvon rasmlari',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('money', 'Pul'), ('food', 'Oziq-ovqat'), ('medicine', 'Dori-darmon'), ('equipment', 'Uskuna'), ('other', 'Boshqa')], max_length=50, verbose_name='Xayriya turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tarif')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('delivered', 'Yetkazib berilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonim')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Xabar')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='donation_receipts/', verbose_name='Chek rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Xayriyachi')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='animals.shelter', verbose_name='Boshpana')),
            ],
            options={
                'verbose_name': 'Xayriya',
                'verbose_name_plural': 'Xayriyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Juda yomon'), (2, '2 - Yomon'), (3, "3 - O'rtacha"), (4, '4 - Yaxshi'), (5, '5 - Juda yaxshi')], verbose_name='Reyting')),
                ('comment', models.TextField(verbose_name='Sharh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='animals.shelter', verbose_name='Boshpana')),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='animals.veterinarian', verbose_name='Veterinariya')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'shelter'), ('user', 'veterinarian')},
            },
        ),
    ]
